[package]
name = "pencil"
version = "0.1.2"
authors = ["Shipeng Feng <fsp261@gmail.com>"]
keywords = ["web", "framework"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/fengsp/pencil"
homepage = "https://github.com/fengsp/pencil"
documentation = "http://fengsp.github.io/pencil/"
description = "A micro web framework for Rust."

[dependencies]
hyper = "0.8.0"
regex = "0.1.58"
rustc-serialize = "0.3.18"
url = "0.5.7"
log = "0.3.5"
formdata = "0.7.9"
handlebars = "0.16.0"
typemap = "0.3.3"
mime = "0.2.0"
mime_guess = "1.6.0"
