[package]
name = "pencil"
version = "0.1.0"
authors = ["Shipeng Feng <fsp261@gmail.com>"]
keywords = ["web", "framework"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/fengsp/pencil"
homepage = "https://github.com/fengsp/pencil"
documentation = "http://fengsp.github.io/pencil/"
description = "A microframework for Rust."

[dependencies]
hyper = "*"
regex = "*"
rustc-serialize = "*"
url = "*"
log = "*"
formdata = "*"
handlebars = "0.12.1"
anymap = "*"
